### ISSUE TITLE
[BUG] Error: Parameter token or opts.auth is required on PR

### ISSUE THREAD

**Issue by ZoranPandovski** [cla-assistant/github-action#55]
**Describe the bug**
We are using the v2.0.0-alpha version. When someone makes a pull request the bellow error is shown. Note that this works for some users, so it's quite random.

```
home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1
module.exports=function(e,t){"use strict";var r={};function __webpack_require__(t){if(r[t]){return r[t].exports}var n=r[t]={i:t,l:false,exports:{}};e[t].call(n.exports,n,n.exports,__webpack_require__);n.l=true;return n.exports}__webpack_require__.ab=__dirname+"/";function startup(){return __webpack_require__(131)}t(__webpack_require__);return startup()}({11:function(e){e.exports=wrappy;function wrappy(e,t){if(e&&t)return wrappy(e)(t);if(typeof e!=="function")throw new TypeError("need wrapper function");Object.keys(e).forEach(function(t){wrapper[t]=e[t]});return wrapper;function wrapper(){var t=new Array(arguments.length);for(var r=0;r<t.length;r++){t[r]=arguments[r]}var n=e.apply(this,t);var o=t[t.length-1];if(typeof n==="function"&&n!==o){Object.keys(o).forEach(function(e){n[e]=o[e]})}return n}}},16:function(e){e.exports=require("tls")},18:function(){eval("require")("encoding")},49:function(e,t,r){var n=r(11);e.exports=n(once

Error: Parameter token or opts.auth is required
    at Object.getAuthString (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:3726)
    at Object.getOctokitOptions (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:65319)
    at Object.getOctokit (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:54767)
    at Object.994 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:221556)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:154)
    at Object.407 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:25532)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:154)
    at Object.210 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:12044)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:154)
    at Object.131 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:5235)home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1
module.exports=function(e,t){"use strict";var r={};function __webpack_require__(t){if(r[t]){return r[t].exports}var n=r[t]={i:t,l:false,exports:{}};e[t].call(n.exports,n,n.exports,__webpack_require__);n.l=true;return n.exports}__webpack_require__.ab=__dirname+"/";function startup(){return __webpack_require__(131)}t(__webpack_require__);return startup()}({11:function(e){e.exports=wrappy;function wrappy(e,t){if(e&&t)return wrappy(e)(t);if(typeof e!=="function")throw new TypeError("need wrapper function");Object.keys(e).forEach(function(t){wrapper[t]=e[t]});return wrapper;function wrapper(){var t=new Array(arguments.length);for(var r=0;r<t.length;r++){t[r]=arguments[r]}var n=e.apply(this,t);var o=t[t.length-1];if(typeof n==="function"&&n!==o){Object.keys(o).forEach(function(e){n[e]=o[e]})}return n}}},16:function(e){e.exports=require("tls")},18:function(){eval("require")("encoding")},49:function(e,t,r){var n=r(11);e.exports=n(once

Error: Parameter token or opts.auth is required
    at Object.getAuthString (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:3726)
    at Object.getOctokitOptions (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:65319)
    at Object.getOctokit (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:54767)
    at Object.994 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:221556)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:154)
    at Object.407 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:25532)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:154)
    at Object.210 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:12044)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:154)
    at Object.131 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.0-alpha/lib/main.js:1:5235)
```

**To Reproduce**
Check this [PR](https://github.com/mindsdb/mindsdb/pull/746)

**Comment by ibakshay** [comment]
Hi @ZoranPandovski, Thank you for reaching out to us.. 
I think I have found the issue :). 

In the [CLA workflow file](https://github.com/mindsdb/mindsdb/blob/staging/.github/workflows/cla.yml), you have to trigger the CLA workflow for `pull_request_target` event but not for `pull_request` event.

This event `pull_request_target` is introduced by GitHub recently in order to support the PR from forked repositories. I think you also face this issue only when the PR is coming from the forks. You can read more about `pull_request_target` event [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target)

So your workflow file should be modified as follows: 

```yaml
name: "MindsDB CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]
```

**Comment by ZoranPandovski** [comment]
Thanks, @ibakshay for the response. I will change the event, in case the issue still happens I will reopen the issue.

**Comment by ibakshay** [comment]
@ZoranPandovski, sure, sounds good..

**Comment by rsbeckerca** [comment]
This fix did not help in my repo. Any other options?

**Comment by stardiviner** [comment]
I got same error on my workflow https://github.com/stardiviner/kiwix.el/pull/7/checks
My workflow is correct as @ibakshay mentioned.
