### ISSUE TITLE
[BUG] Exception when executing the cla-assistant during pull - Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by rsbeckerca** [cla-assistant/github-action#71]
**Describe the bug**
Getting a `Parameter token or opts.auth is required` error when the `cla-assistant` is run when a pull request is created, whether there is another pull request with the **I have read the CLA Document and I hereby sign the CLA** comment in a separate pull request comment. Currently on V2.0.3-alpha. The repo where this is being tested is rsbeckerca/TestCLA. I am suspecting that there is a step missing in the setup. Also the repo uses a **main** branch instead of a **master** branch.

**To Reproduce**

1. Create a new repo.
2. Add the cla-assistant workflow `cla.yml` file.
3. Switch to a new branch
4. Modify a file and commit.
5. Create a pull request.

**Expected behavior**
The exception should not occur.

**Screenshots**
Error: Parameter token or opts.auth is required
    at Object.getAuthString (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:4610)
    at Object.getOctokitOptions (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:68637)
    at Object.getOctokit (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:57376)
    at Object.994 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:226648)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:154)
    at Object.407 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:27687)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:154)
    at Object.210 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:12928)
    at __webpack_require__ (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:154)
    at Object.131 (/home/runner/work/_actions/cla-assistant/github-action/v2.0.3-alpha/lib/main.js:1:6119)

**Comment by ibakshay** [comment]
Hi @AndrewGable, thank you for reaching out to us. 
Did you add your [Personal Access token with repo scope](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) into the test repository `rsbeckerca/TestCLA` secrets ? 

<img width="1770" alt="Screenshot 2021-02-01 at 08 06 18" src="https://user-images.githubusercontent.com/33329946/106425860-d94ad780-6464-11eb-904d-1faa661f36f3.png">

I think this is causing the issue.

**Comment by rsbeckerca** [comment]
Thanks. That was it.
